### PR TITLE
Lets add support for first Yosemite Beta

### PR DESCRIPTION
**Pull request by rhcp011235**

### CODE REVIEW

**Comment by w0lfschild** [comment]
Sure.

**Comment by rhcp011235** [comment]
worked fine for me and others

that's why I duplicated it.

On Saturday, November 8, 2014, Wolfgang Baird notifications@github.com
wrote:

> Sure. The way you implemented it though wouldn't work.
> 
> Needs to be >= 10.10 not simply = 10.10.1
> 
> Since the version number is a string and not a number you need to use
> something to compare the individual parts.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/w0lfschild/DarkBoot/pull/1#issuecomment-62288697.

## 

Sent from my iPhone

**Comment by w0lfschild** [comment]
Woops actually you're right I thought you'd replaced the 10.10 check with a 10.10.1 one rather than add another check.

Regardless I've updated it with any version 10.10 or above.

**Comment by rhcp011235** [comment]
:)

On Saturday, November 8, 2014, Wolfgang Baird notifications@github.com
wrote:

> Woops actually you're right I thought you'd replaced the 10.10 check with
> a 10.10.1 one rather than add another check.
> 
> Regardless I've updated it with any version 10.10 or above.
> 
> —
> Reply to this email directly or view it on GitHub
> https://github.com/w0lfschild/DarkBoot/pull/1#issuecomment-62289299.

## 

Sent from my iPhone

**Pull request closed without merging**
